packages:
  - .

catalog:
  '@cloudflare/workers-types': ^4.20260526.1
  '@opennextjs/cloudflare': ^1.19.11
  '@types/node': ^25.7.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  next: 16.2.6
  nuqs: ^2.8.9
  react: 19.2.6
  react-dom: 19.2.6
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.22
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.22
  wrangler: ^4.93.0

ignoredBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - '@cloudflare/workers-types'

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
